# Generated by Django 4.0.5 on 2023-05-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
