# Generated by Django 4.0.5 on 2023-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clickCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
